### ISSUE TITLE
Build without devmapper

### ISSUE THREAD

**Issue by mands** [nstack/skopeo#1]
## Problem
* current skopeo builds use devmapper, we don't need this and causes a slight issue on older RH-distros (e.g. F25 used on Jenkins)
* can be worked around as per https://github.com/shipyard/shipyard-agent/issues/6

**Comment by jonboulle** [comment]
Since we're not using any of the containers/storage stuff turns out we can fairly trivially disable it all using `containers_image_ostree_stub` build flag (added via https://github.com/containers/image/pull/362/files) - which results in a much simpler binary.

**Comment by jonboulle** [comment]
Added https://github.com/nstack/skopeo/commit/ccc4c266f9caf0049beb2287b3bbac8ac0a0be5c to our master, and the quayfix branch (which is currently the only place we diverge from master), and pushed a new release (with a more sensible naming scheme)  @ https://github.com/nstack/skopeo/releases/tag/v0.1.27-dev%2B0f061038
